### ISSUE TITLE
semantik-d does not use translations from semantik.mo

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ita1024/semantik#50]
```
What steps will reproduce the problem?
1. run semantik-d
2. missing translations

What version of the product are you using?
Semantik-0.9.1

```

Original issue reported on code.google.com by `loginov.alex.valer@gmail.com` on 7 Feb 2015 at 10:44

**Comment by glixx** [comment]
For spec file (RPM package):
```
for lang in `ls build/src/po|cut -d "." --fields=1`
do
  ln -s %{name}.mo %{buildroot}%{_datadir}/locale/$lang/LC_MESSAGES/%{name}-d.mo
done
```

**Comment by ita1024** [comment]
Yes, unfortunately the .mo file would not be used at runtime even when we install it.

**Comment by glixx** [comment]
Will you install symlinks?

**Comment by ita1024** [comment]
What do you mean?

**Comment by glixx** [comment]
For all lang in /usr/share/locale/lang/LC_MESSAGES while installation:
ln -s semantik.mo semantik-d.mo

**Comment by ita1024** [comment]
Does any translation appear when you do that?

**Comment by glixx** [comment]
Yes, after this semantik-d is localized.

**Comment by ita1024** [comment]
Somehow the menus are not localized.

**Comment by glixx** [comment]
It OK for Russian with symlinks.
![num03](https://cloud.githubusercontent.com/assets/2681872/11324248/4737ee32-913d-11e5-8e05-5de4c3ef2b2e.png)

**Comment by ita1024** [comment]
4832adcda79b89e41560690357fdf954460ff5c0
