### ISSUE TITLE
gzipped-svg-icon

### ISSUE THREAD

**Issue by glixx** [ita1024/semantik#55]
semantik.i586: W: gzipped-svg-icon /usr/share/icons/oxygen/scalable/apps/semantik-d.svgz
semantik.i586: W: gzipped-svg-icon /usr/share/icons/oxygen/scalable/apps/semantik.svgz

**Comment by ita1024** [comment]
?

**Comment by glixx** [comment]
It's rpmlint warning.

Not all desktop environments that support SVG icons support them gzipped (.svgz). Install the icon as plain uncompressed SVG.

**Comment by ita1024** [comment]
If it can make you happy... 567597fb1d073b286ec9f76097a2b20c591a026d
