### ISSUE TITLE
Twice filename for download

### ISSUE THREAD

**Issue by glixx** [ita1024/semantik#56]
If to download file from https://github.com/ita1024/semantik/releases, then filename is "semantik-semantik-0.9.4.tar.gz", but should be "semantik-0.9.4.tar.gz"

**Comment by ita1024** [comment]
How do you see such a thing? The releases can be obtained from https://waf.io/semantik-0.9.4.tar.bz2 ; we do not provide files on Github.

**Comment by glixx** [comment]
Please fix github settings. For example https://github.com/viktor-zin/afce/releases is OK.

**Comment by ita1024** [comment]
Show me how. We are not using github except for the source settings.

**Comment by glixx** [comment]
I think tag: "v0.9.4" instead of "semantik-0.9.4", but I'm not sure.

**Comment by ita1024** [comment]
We are not using the "release" functionality, and we have no intention to use the github tag conventions.
