### ISSUE TITLE
Move from google code

### ISSUE THREAD

**Issue by glixx** [ita1024/semantik#58]
google code is read only, but there are urls in code on code.google.com:

grep -r google
src/main.cpp:   l_o.setBugAddress("http://code.google.com/p/semantik/issues/list");
src/po/semantik.pot:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/ru.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/messages.sh:BUGADDR="http://code.google.com/p/semantik/issues"   # MSGID-Bugs
src/po/sk.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/es.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/fr.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/cs.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/po/el.po:"Report-Msgid-Bugs-To: http://code.google.com/p/semantik/issues\n"
src/fig/semd.cpp:       l_o.setBugAddress("http://code.google.com/p/semantik/issues/list");
src/templates/s5/ui/default/semantik.css: * http://code.google.com/p/semantik/

**Comment by ita1024** [comment]
55ef21cf078cedc8573a5e1bd88a84e085606403

**Comment by glixx** [comment]
You fixed 9 files, but should be 11 files.

**Comment by ita1024** [comment]
Yes, done.
