### ISSUE TITLE
non-executable-script

### ISSUE THREAD

**Issue by glixx** [ita1024/semantik#59]
https://fedoraproject.org/wiki/Packaging_tricks

semantik.i586: W: non-executable-script /usr/share/apps/semantik/templates/pdflatex/wscript 0644L /usr/bin/python
semantik.i586: W: non-executable-script /usr/share/apps/semantik/sembind.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/filters/others.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/filters/main.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/filters/kdissert.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/filters/fvym.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/filters/semantik.py 0644L /usr/bin/env
semantik.i586: W: non-executable-script /usr/share/apps/semantik/templates/beamer/wscript 0644L /usr/bin/python

**Comment by ita1024** [comment]
What's the matter? Those files are not meant to be executable.

**Comment by glixx** [comment]
In this case to delete shebang:
https://fedoraproject.org/wiki/Packaging_tricks#Remove_shebang_from_Python_libraries
https://fedoraproject.org/wiki/Packaging_tricks#Remove_shebang_from_files

**Comment by ita1024** [comment]
No, we will not remove the shebang lines. Those help for syntax highlighting in my editor.
