### ISSUE TITLE
german version crashes on both Debian and OpenSuse

### ISSUE THREAD

**Issue by ddhh83** [ita1024/semantik#61]
I just changed my system's language to Canadian English and realized that it doesn't crash when I right click the map and select "add an element". In the German versions of both OpenSuse Leap (installed from the repos) and Debian Jessie 8.2 KDE (compiled from source, because not in the repos) it did.
As there's three possibilities to add an element, maybe just deleting this option would be a quick and sound solution.
Thanks for the great program!

**Comment by ita1024** [comment]
No crash here, which version of the source code are you building?

**Comment by ddhh83** [comment]
it's the new one 0.9.5 from here on Debian 8.2.0 with KDE 4.14. (German language as default). As said, since I changed locales to en_CA.UTF8 the problem disappeared.
I linked the problem to German language, because on openSuse I had exactly the same problem (I think it's version 0.9.4 in the repos there).

**Comment by ita1024** [comment]
It seems that we have forgotten to release the version 0.9.5, the problem was solved a long time ago.
