### ISSUE TITLE
It's time for qt5

### ISSUE THREAD

**Issue by glixx** [ita1024/semantik#62]
Qt4 is EOL.

**Comment by ita1024** [comment]
I have tried KDE 5 several times, but I still have lots of problems with it, so i am not in a hurry for this.

**Comment by glixx** [comment]
Qt5 can be used without KDE 5 dependencies.
Semantik will be deleted from repos if to do nothing, distros update on KDE 5.

**Comment by ita1024** [comment]
FreeBSD does not have KDE5 yet.

**Comment by xandark** [comment]
Ultimately, KDE5 is the future, and all the issues will be worked out, just as they were with KDE4.

**Comment by ita1024** [comment]
@xandark You must have meant "Unfortunately".

The code was ported to KDE5 a while ago so we are closing this now.

**Comment by baimafeima** [comment]
@ita1024 
First of all thank you for developing such a great piece of software. I would like to continue using it and have requested its addition the Solus repositories here: https://dev.solus-project.com/T2819

Unfortunately, I was informed that it relies on QtWebKit for Qt4 and unless this is dropped or it gets ported to Qt5, it cannot be included in the repositories. What are your plans and ETA regarding this? Many thanks.

**Comment by ita1024** [comment]
Use the code from the master branch.

**Comment by c-cesar** [comment]
Maybe Semantik works with QtWebKit-ng. https://github.com/annulen/webkit
Porting the code away from webkit can be almost impossible, but webkit is being ported to Qt 5.
