### ISSUE TITLE
Unable to build on Ubuntu 16.10

### ISSUE THREAD

**Issue by xantof** [ita1024/semantik#64]
Long time user that cannot live without Semantik.  2 brand new 16.10 installs.  Unable to build on either.

[Semantik1InstallOutput.txt](https://github.com/ita1024/semantik/files/597291/Semantik1InstallOutput.txt)
[Semantik1Log.txt](https://github.com/ita1024/semantik/files/597292/Semantik1Log.txt)

I'm not a noob (without being an expert) but I've always found it hard to build/install Semantik at every software upgrade/hardware change.  There are dependencies that I can never seem to find (where are those damned -debug files ! for example...).

Would love to have a fully packaged Semantik or a PPA.

In the meantime, any hint on how I should proceed?

Appreciative of your work - the 2 of you !

Stephan

**Comment by ita1024** [comment]
Works for me on Ubuntu 16.04. Make sure to install python-dev, kdelibs5-dev, libphonon-dev and kdelibs-bin.

If you are on a version that has KDE5, then clone this repository and build Semantik from source. You will then need python-dev and all the libKF5 that you can find.

**Comment by xantof** [comment]
Finally managed to install 0.9.5 !
Was facing "QtWebKit not found - Semantik requires Qt >= 4.4" message. Installed libqtwebkit-dev.
Was facing "Could not find the program ['kde4-config']" message.  Installed python-kde4.
Was facing "could not open /usr/share/kde4/apps/cmake/modules/KDELibsDependencies.cmake" message.
Installed kdelibs5-dev, kdelibs5-dev, libkf5kdelibs4support5. [not sure which package did the trick].

Ta-ta ! 0.9.5 Built OK!

Now some work with working version, then onto 1.0.0 with KF.

Love what you do. Wish there was an install package with automatic dependencies resolution.
Stephan

**Comment by ita1024** [comment]
That should be something for the package management system.
