### ISSUE TITLE
Build fails with Qt 5.7

### ISSUE THREAD

**Issue by c-cesar** [ita1024/semantik#65]
in `src/fig/semantik_d_win.cpp` we have various of this action declarations: `KStandardAction::save(this, NULL, actionCollection());` and this fails to build because Qt expects a slot or a string with a slot name, not a NULL value.
If I use `KStandardAction::save(this, SLOT(any_name()), actionCollection());` the compilation succeeds, but I get runtime errors saing that I don't have the slot. I'm using this as a workaround to use Semantik right now.
As I don't know the slots names and locations I can't fix it myself right now. 

A bit out of topic, I suggest to use the declaration in this format, to get compile time check:
`KStandardAction::save(this, save(), actionCollection())`

**Comment by ita1024** [comment]
It works fine in Qt 5.5.1 here (Ubuntu).

**Comment by a17r** [comment]
It still fails to build with Qt-5.7, so why is this closed? Workaround is to build with `-std=c++11`.

**Comment by c-cesar** [comment]
Compilation works for me with referenced commit, without special flags.
Maybe the fix breaks compatibility with older GCC versions.
What are you using? Mine are: GCC 6.3 & Qt 5.7

**Comment by a17r** [comment]
That works, because GCC 6.3 is using C++14 by default instead of C++98. Qt-5.7 expects at least C++11, that's why many packages fail to build on earlier GCC versions unless -std=c++11 is passed.

Now, that does not explain the __builtin_isnan failure, but I haven't looked at the code yet. Probably some not so ideal header ifdef?

**Comment by ita1024** [comment]
@a17r This is unrelated to this matter. Please do not post on old tickets; open a new one and attach error messages, system information and config.log files.
