### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by JonnyMako** [ita1024/semantik#68]
My build fails :(

Build failed
 -> task in 'semlib' failed with exit status 1: 
	{task 140249365594544: qxx sembind_py.cpp -> sembind_py.cpp.1.o}
['/usr/bin/g++', '-O2', '-pipe', '-Wall', '-std=c++11', '-fPIC', '-fPIC', '-march=x86-64', '-mtune=generic', '-fstack-protector-strong', '-fwrapv', '-I.', '-I..', '-Isrc', '-I../src', '-Isrc/fig', '-I../src/fig', '-Isrc/base', '-I../src/base', '-I/usr/lib/qt/mkspecs/linux-g++', '-I/usr/include/KF5/KIOCore', '-I/usr/include/KF5/KAuth', '-I/usr/include/KF5/KIOWidgets', '-I/usr/include/KF5/KIconThemes', '-I/usr/include/KF5/KConfigWidgets', '-I/usr/include/KF5/KXmlGui', '-I/usr/include/KF5/KCoreAddons', '-I/usr/include/KF5/KConfigGui', '-I/usr/include/KF5/KConfigCore', '-I/usr/include/KF5/KWidgetsAddons', '-I/usr/include/KF5/KI18n', '-I/usr/include/KF5/KDELibs4Support', '-I/usr/include/qt/QtCore', '-I/usr/include/qt', '-I/usr/include/qt/QtWidgets', '-I/usr/include/qt/QtGui', '-I/usr/include/qt/QtWebKit', '-I/usr/include/qt/QtNetwork', '-I/usr/include/qt/QtXml', '-I/usr/include/qt/QtPrintSupport', '-I/usr/include/qt/QtSvg', '-I/usr/include/python3.6m', '-DWAF', '-DGAP=50', '-DNDEBUG', '../src/base/sembind_py.cpp', '-c', '-o/home/jmk/usr/local/share/semantik/build/src/base/sembind_py.cpp.1.o']
 -> task in 'semlib' failed with exit status 1: 
	{task 140249365569400: qxx sem_mediator.cpp -> sem_mediator.cpp.1.o}
['/usr/bin/g++', '-O2', '-pipe', '-Wall', '-std=c++11', '-fPIC', '-fPIC', '-march=x86-64', '-mtune=generic', '-fstack-protector-strong', '-fwrapv', '-I.', '-I..', '-Isrc', '-I../src', '-Isrc/fig', '-I../src/fig', '-Isrc/base', '-I../src/base', '-I/usr/lib/qt/mkspecs/linux-g++', '-I/usr/include/KF5/KIOCore', '-I/usr/include/KF5/KAuth', '-I/usr/include/KF5/KIOWidgets', '-I/usr/include/KF5/KIconThemes', '-I/usr/include/KF5/KConfigWidgets', '-I/usr/include/KF5/KXmlGui', '-I/usr/include/KF5/KCoreAddons', '-I/usr/include/KF5/KConfigGui', '-I/usr/include/KF5/KConfigCore', '-I/usr/include/KF5/KWidgetsAddons', '-I/usr/include/KF5/KI18n', '-I/usr/include/KF5/KDELibs4Support', '-I/usr/include/qt/QtCore', '-I/usr/include/qt', '-I/usr/include/qt/QtWidgets', '-I/usr/include/qt/QtGui', '-I/usr/include/qt/QtWebKit', '-I/usr/include/qt/QtNetwork', '-I/usr/include/qt/QtXml', '-I/usr/include/qt/QtPrintSupport', '-I/usr/include/qt/QtSvg', '-I/usr/include/python3.6m', '-DWAF', '-DGAP=50', '-DNDEBUG', '../src/base/sem_mediator.cpp', '-c', '-o/home/jmk/usr/local/share/semantik/build/src/base/sem_mediator.cpp.1.o']

[config.log.tar.gz](https://github.com/ita1024/semantik/files/812114/config.log.tar.gz)

**Comment by ita1024** [comment]
Where is the error message from the compiler?

**Comment by JonnyMako** [comment]
I can't find any clues in the log. Is there a debug flag I can set?

**Comment by ita1024** [comment]
You have reproduced only a part of the error message (one command-line); this is insufficient to understand the problem. Please reproduce the complete error message from the compiler.

**Comment by JonnyMako** [comment]
I'm installing using Arch Linux supplimentary package manager frome here:
https://aur.archlinux.org/packages/semantik/

This should take care of all dependencies as listed on the page.

`
$ packer semantik

0 aur/semantik 0.9.4-3 (7)
    A mindmapping-like tool for document generation (reports, thesis, etc)

Type numbers to install. Separate each number with a space.
Numbers: 0

Aur Targets    (1): semantik

Proceed with installation? [Y/n]

Edit semantik PKGBUILD with $EDITOR? [Y/n] n
Edit install with $EDITOR? [Y/n] n
==> Making package: semantik 0.9.4-3 (Mon Mar  6 12:43:31 CST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found semantik-0.9.4.tar.gz
  -> Found install
==> Validating source files with sha256sums...
    semantik-0.9.4.tar.gz ... Passed
    install ... Passed
==> Extracting sources...
  -> Extracting semantik-0.9.4.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Setting top to                           : /tmp/packerbuild-1000/semantik/semantik/src/semantik-semantik-0.9.4 
Setting out to                           : /tmp/packerbuild-1000/semantik/semantik/src/semantik-semantik-0.9.4/build 
Checking for program 'gzip'              : /usr/bin/gzip 
You are using Linux, that's good (tm) 
which: no kde-config in (/home/jmk/.scripts:/home/jmk/.gem/ruby/2.3.0/bin:/home/jmk/.scripts:/home/jmk/.gem/ruby/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
For now Semantik uses a few kde icons - if you have problems seeing the icons install kdebase
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'qmake-qt4'         : /usr/bin/qmake-qt4 
Checking for program 'qmake4'            : not found 
Checking for program 'qmake'             : /usr/bin/qmake 
Checking for program 'uic-qt3'           : not found 
Checking for program 'uic3'              : not found 
Checking for program 'uic-qt4'           : /usr/bin/uic-qt4 
Checking for uic version                 : version 4.8.7 
Checking for program 'moc-qt4'           : /usr/bin/moc-qt4 
Checking for program 'rcc-qt4'           : /usr/bin/rcc-qt4 
Checking for program 'lrelease-qt4'      : /usr/bin/lrelease-qt4 
Checking for program 'lupdate-qt4'       : /usr/bin/lupdate-qt4 
Found the Qt4 libraries in               : /usr/lib 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'QtCore_debug'              : not found 
Checking for 'QtGui_debug'               : not found 
Checking for 'QtUiTools_debug'           : not found 
Checking for 'QtNetwork_debug'           : not found 
Checking for 'QtOpenGL_debug'            : not found 
Checking for 'QtSql_debug'               : not found 
Checking for 'QtSvg_debug'               : not found 
Checking for 'QtTest_debug'              : not found 
Checking for 'QtXml_debug'               : not found 
Checking for 'QtXmlPatterns_debug'       : not found 
Checking for 'QtWebKit_debug'            : not found 
Checking for 'Qt3Support_debug'          : not found 
Checking for 'QtHelp_debug'              : not found 
Checking for 'QtScript_debug'            : not found 
Checking for 'QtDeclarative_debug'       : not found 
Checking for 'QtDesigner_debug'          : not found 
Checking for 'QtCore'                    : yes 
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : not found 
Checking for 'Qt3Support'                : yes 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Checking for 'QtDesigner'                : yes 
Checking for program 'python'            : /usr/bin/python 
QtWebKit not found - Semantik requires Qt >= 4.4 
(complete log in /tmp/packerbuild-1000/semantik/semantik/src/semantik-semantik-0.9.4/build/config.log)
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd05c0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd0588>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd0550>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd0518>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd04e0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd04a8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd0470>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x7f7f23bd0400>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
==> ERROR: A failure occurred in build().
    Aborting...
The build failed.
`

**Comment by ita1024** [comment]
So the build is not failing but the configuration is. The problem is `QtWebKit not found - Semantik requires Qt >= 4.4 ` so go and install qtwebkit.

Also, Python 3.6 has a regression and displays unnecessary warnings which you can ignore.
