### ISSUE TITLE
Current blockers for inclusion into the Solus repositories

### ISSUE THREAD

**Issue by baimafeima** [ita1024/semantik#69]
I have suggested Semantik to be included into the Solus repositories: https://dev.solus-project.com/T2819
It is currently on hold due to the following issues according to one of the developers: 

> This relies on QtWebKit for Qt4, so it'll need to either drop that or get ported to Qt5 first.

How is the porting to Qt5 progressing? Could you make a new release here on GitHub when it is completed? Thank you.

**Comment by ita1024** [comment]
Use the master branch, there is no release because some features are broken by this unnecessary mess. The application does not crash like KDE still does, but there will be no release until it is ready.

Note: we do not make new releases on Github.

**Comment by baimafeima** [comment]
Thanks for your feedback. The master branch is not eligible for inclusion. I will wait until the next release and inform the Solus project then.
