### ISSUE TITLE
confusing instructions regarding package dependencies

### ISSUE THREAD

**Issue by ruediman** [ita1024/semantik#70]
Hi Thomas,
I really love Semantik!!!
So I would be especially delighted if you could shed some light on which packages we need, in order to build semantik 0.9.5 on Xubuntu 16.04? Or what am I doing wrong? I think that I could install python-distutils ...
This is my log:

---
xxx:~/Downloads/semantik-0.9.5$ ./waf configure build
Setting top to                           : /home/xxx/Downloads/semantik-0.9.5 
Setting out to                           : /home/xxx/Downloads/semantik-0.9.5/build 
Checking for program 'gzip'              : /bin/gzip 
You are using Linux, that's good (tm) 
For now Semantik uses a few kde icons - if you have problems seeing the icons install kdebase
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'qmake-qt4'         : /usr/bin/qmake-qt4 
Checking for program 'qmake4'            : not found 
Checking for program 'qmake'             : /usr/bin/qmake 
Checking for program 'uic-qt3'           : not found 
Checking for program 'uic3'              : /usr/bin/uic3 
Checking for program 'uic-qt4'           : /usr/bin/uic-qt4 
Checking for uic version                 : version 4.8.7 
Checking for program 'moc-qt4'           : /usr/bin/moc-qt4 
Checking for program 'rcc-qt4'           : not found 
Checking for program 'rcc'               : /usr/bin/rcc 
Checking for program 'lrelease-qt4'      : /usr/bin/lrelease-qt4 
Checking for program 'lupdate-qt4'       : /usr/bin/lupdate-qt4 
Found the Qt4 libraries in               : /usr/lib/x86_64-linux-gnu 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'QtCore_debug'              : not found 
Checking for 'QtGui_debug'               : not found 
Checking for 'QtUiTools_debug'           : not found 
Checking for 'QtNetwork_debug'           : not found 
Checking for 'QtOpenGL_debug'            : not found 
Checking for 'QtSql_debug'               : not found 
Checking for 'QtSvg_debug'               : not found 
Checking for 'QtTest_debug'              : not found 
Checking for 'QtXml_debug'               : not found 
Checking for 'QtXmlPatterns_debug'       : not found 
Checking for 'QtWebKit_debug'            : not found 
Checking for 'Qt3Support_debug'          : not found 
Checking for 'QtHelp_debug'              : not found 
Checking for 'QtScript_debug'            : not found 
Checking for 'QtDeclarative_debug'       : not found 
Checking for 'QtDesigner_debug'          : not found 
Checking for 'QtCore'                    : yes 
Checking for 'QtGui'                     : yes 
Checking for 'QtUiTools'                 : yes 
Checking for 'QtNetwork'                 : yes 
Checking for 'QtOpenGL'                  : yes 
Checking for 'QtSql'                     : yes 
Checking for 'QtSvg'                     : yes 
Checking for 'QtTest'                    : yes 
Checking for 'QtXml'                     : yes 
Checking for 'QtXmlPatterns'             : yes 
Checking for 'QtWebKit'                  : yes 
Checking for 'Qt3Support'                : yes 
Checking for 'QtHelp'                    : yes 
Checking for 'QtScript'                  : yes 
Checking for 'QtDeclarative'             : yes 
Checking for 'QtDesigner'                : yes 
Checking for program 'python'            : /usr/bin/python 
Checking for python version              : (2, 7, 12, 'final', 0) 
python-config                            : not found 
Checking for library python2.7 in LIBDIR : not found 
Checking for library python2.7 in python_LIBPL : yes 
Checking for header Python.h                   : Distutils not installed? Broken python installation? Get python-config now!

**Comment by ita1024** [comment]
Start by cloning https://github.com/ita1024/semantik.git because there will be a new release soon.

Then make sure python3-devel and most kde development packages are installed. I do not have a complete list of the packages to install.

**Comment by ruediman** [comment]
Hi - thanks for your help! much appreciated :)
I now fiddled around quite a bit with different packages (Qt5. kde, etc) but still no luck.
Would it be possible to get some more assistance? How to get there?
Here again my log... 

xxx:~/Downloads/semantik-master$ sudo ./waf configure build
Setting top to                           : /home/xxx/Downloads/semantik-master 
Setting out to                           : /home/xxx/Downloads/semantik-master/build 
Checking for program 'msgfmt'            : /usr/bin/msgfmt 
Checking for program 'gzip'              : /bin/gzip 
You are using Linux, that's good (tm) 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'qmake-qt5'         : not found 
Checking for program 'qmake5'            : not found 
Checking for program 'qmake'             : /usr/bin/qmake 
Checking for program 'uic-qt5'           : not found 
Checking for program 'uic'               : /usr/lib/x86_64-linux-gnu/qt5/bin/uic 
Checking for uic version                 : uic 5.5.1 
Checking for program 'moc-qt5'           : not found 
Checking for program 'moc'               : /usr/lib/x86_64-linux-gnu/qt5/bin/moc 
Checking for program 'rcc-qt5'           : not found 
Checking for program 'rcc'               : /usr/lib/x86_64-linux-gnu/qt5/bin/rcc 
Checking for program 'lrelease-qt5'      : not found 
Checking for program 'lrelease'          : /usr/bin/lrelease 
Checking for program 'lupdate-qt5'       : not found 
Checking for program 'lupdate'           : /usr/bin/lupdate 
Found the Qt5 libraries in               : /usr/lib/x86_64-linux-gnu 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'Qt5OpenGL_DEBUG'           : not found 
Checking for 'Qt5Concurrent_DEBUG'       : not found 
Checking for 'Qt5Script_DEBUG'           : not found 
Checking for 'Qt5ScriptTools_DEBUG'      : not found 
Checking for 'Qt5Script_DEBUG'           : not found 
Checking for 'Qt5Gui_DEBUG'              : not found 
Checking for 'Qt5Network_DEBUG'          : not found 
Checking for 'Qt5Xml_DEBUG'              : not found 
Checking for 'Qt5ScriptTools_DEBUG'      : not found 
Checking for 'Qt5XmlPatterns_DEBUG'      : not found 
Checking for 'Qt5EglDeviceIntegration_DEBUG' : not found 
Checking for 'Qt5Gui_DEBUG'                  : not found 
Checking for 'Qt5DBus_DEBUG'                 : not found 
Checking for 'Qt5Core_DEBUG'                 : not found 
Checking for 'Qt5Sql_DEBUG'                  : not found 
Checking for 'Qt5OpenGL_DEBUG'               : not found 
Checking for 'Qt5CLucene_DEBUG'              : not found 
Checking for 'Qt5QuickTest_DEBUG'            : not found 
Checking for 'Qt5PrintSupport_DEBUG'         : not found 
Checking for 'Qt5Core_DEBUG'                 : not found 
Checking for 'Qt5Quick_DEBUG'                : not found 
Checking for 'Qt5DBus_DEBUG'                 : not found 
Checking for 'Qt5Designer_DEBUG'             : not found 
Checking for 'Qt5WebKitWidgets_DEBUG'        : not found 
Checking for 'Qt5Test_DEBUG'                 : not found 
Checking for 'Qt53Support_DEBUG'             : not found 
Checking for 'Qt5ExtSerialPort_DEBUG'        : not found 
Checking for 'Qt5XcbQpa_DEBUG'               : not found 
Checking for 'Qt5QuickParticles_DEBUG'       : not found 
Checking for 'Qt5Xml_DEBUG'                  : not found 
Checking for 'Qt5DesignerComponents_DEBUG'   : not found 
Checking for 'Qt5Test_DEBUG'                 : not found 
Checking for 'Qt5Help_DEBUG'                 : not found 
Checking for 'Qt5WebKit_DEBUG'               : not found 
Checking for 'Qt5Designer_DEBUG'             : not found 
Checking for 'Qt5CLucene_DEBUG'              : not found 
Checking for 'Qt5Qml_DEBUG'                  : not found 
Checking for 'Qt5Sql_DEBUG'                  : not found 
Checking for 'Qt5Svg_DEBUG'                  : not found 
Checking for 'Qt5Widgets_DEBUG'              : not found 
Checking for 'Qt5Declarative_DEBUG'          : not found 
Checking for 'Qt5Network_DEBUG'              : not found 
Checking for 'Qt5QuickWidgets_DEBUG'         : not found 
Checking for 'Qt5DesignerComponents_DEBUG'   : not found 
Checking for 'Qt5WebKit_DEBUG'               : not found 
Checking for 'Qt5Help_DEBUG'                 : not found 
Checking for 'Qt5OpenGL'                     : yes 
Checking for 'Qt5Concurrent'                 : yes 
Checking for 'Qt5Script'                     : yes 
Checking for 'Qt5ScriptTools'                : yes 
Checking for 'Qt5Script'                     : yes 
Checking for 'Qt5Gui'                        : yes 
Checking for 'Qt5Network'                    : yes 
Checking for 'Qt5Xml'                        : yes 
Checking for 'Qt5ScriptTools'                : yes 
Checking for 'Qt5XmlPatterns'                : not found 
Checking for 'Qt5EglDeviceIntegration'       : yes 
Checking for 'Qt5Gui'                        : yes 
Checking for 'Qt5DBus'                       : yes 
Checking for 'Qt5Core'                       : yes 
Checking for 'Qt5Sql'                        : yes 
Checking for 'Qt5OpenGL'                     : yes 
Checking for 'Qt5CLucene'                    : yes 
Checking for 'Qt5QuickTest'                  : yes 
Checking for 'Qt5PrintSupport'               : yes 
Checking for 'Qt5Core'                       : yes 
Checking for 'Qt5Quick'                      : yes 
Checking for 'Qt5DBus'                       : yes 
Checking for 'Qt5Designer'                   : not found 
Checking for 'Qt5WebKitWidgets'              : yes 
Checking for 'Qt5Test'                       : yes 
Checking for 'Qt53Support'                   : not found 
Checking for 'Qt5ExtSerialPort'              : not found 
Checking for 'Qt5XcbQpa'                     : yes 
Checking for 'Qt5QuickParticles'             : yes 
Checking for 'Qt5Xml'                        : yes 
Checking for 'Qt5DesignerComponents'         : not found 
Checking for 'Qt5Test'                       : yes 
Checking for 'Qt5Help'                       : yes 
Checking for 'Qt5WebKit'                     : yes 
Checking for 'Qt5Designer'                   : not found 
Checking for 'Qt5CLucene'                    : yes 
Checking for 'Qt5Qml'                        : yes 
Checking for 'Qt5Sql'                        : yes 
Checking for 'Qt5Svg'                        : not found 
Checking for 'Qt5Widgets'                    : yes 
Checking for 'Qt5Declarative'                : not found 
Checking for 'Qt5Network'                    : yes 
Checking for 'Qt5QuickWidgets'               : yes 
Checking for 'Qt5DesignerComponents'         : not found 
Checking for 'Qt5WebKit'                     : yes 
Checking for 'Qt5Help'                       : yes 
See if Qt files compile                      : no 
See if Qt files compile with -fPIE           : no 
See if Qt files compile with -fPIC           : yes 
Checking for code snippet                    : yes 
Checking for program 'python3'               : /usr/bin/python3 
Checking for program 'python'                : /usr/bin/python3 
Could not find Qt5Svg - Semantik requires Qt >= 5
(complete log in /home/xxx)

**Comment by ita1024** [comment]
Try and install a package called qtsvg or qt5svg.

**Comment by ruediman** [comment]
Hi there,
thanks for helping. I did not find any package with the proposed string; so I went ahead and installed anything related.
With that the error message changed to:
`"Could not find Qt5WebEngineWidgets - check `pkg-config --libs Qt5WebEngineWidgets`"`

After some googling I found: [Qt dev package does not include webenginewidgets](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1579265)
I this related to our issue?

**Comment by ita1024** [comment]
A few libraries to install (Ubuntu 17.04):
- libqt5webenginewidgets5-dev
- qtwebengine5-dev
- libqt5svg5-dev
- libkf5config-dev
- libkf5sonnet-dev
- qttools5-dev-tools
- qtbase5-dev-tools

**Comment by ruediman** [comment]
Hi, thanks for coming back :)
Still no luck same error message - some of the above packages do not exist in Ubuntu xenial:
* libqt5webenginewidgets5-dev
* qtwebengine5-dev

What can I do about it?

Here's part of my log again:
xxx:~/Downloads/semantik-master$ sudo ./waf configure build
Setting top to                           : /home/bitmacs/Downloads/semantik-master 
Setting out to                           : /home/bitmacs/Downloads/semantik-master/build 
Checking for program 'msgfmt'            : /usr/bin/msgfmt 
Checking for program 'gzip'              : /bin/gzip 
You are using Linux, that's good (tm) 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'qmake-qt5'         : not found 
Checking for program 'qmake5'            : not found 
Checking for program 'qmake'             : /usr/bin/qmake 
Checking for program 'uic-qt5'           : not found 
Checking for program 'uic'               : /usr/lib/x86_64-linux-gnu/qt5/bin/uic 
Checking for uic version                 : uic 5.5.1 
Checking for program 'moc-qt5'           : not found 
Checking for program 'moc'               : /usr/lib/x86_64-linux-gnu/qt5/bin/moc 
Checking for program 'rcc-qt5'           : not found 
Checking for program 'rcc'               : /usr/lib/x86_64-linux-gnu/qt5/bin/rcc 
Checking for program 'lrelease-qt5'      : not found 
Checking for program 'lrelease'          : /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease 
Checking for program 'lupdate-qt5'       : not found 
Checking for program 'lupdate'           : /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate 
Found the Qt5 libraries in               : /usr/lib/x86_64-linux-gnu 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for pkg-config version >= '0.1' : yes 
Checking for 'Qt5OpenGL_DEBUG'           : not found 
Checking for 'Qt5Concurrent_DEBUG'       : not found 
Checking for 'Qt5Script_DEBUG'           : not found 
Checking for 'Qt5Multimedia_DEBUG'       : not found 
Checking for 'Qt5ScriptTools_DEBUG'      : not found 
Checking for 'Qt5Script_DEBUG'           : not found 
Checking for 'Qt5Gui_DEBUG'              : not found 
Checking for 'Qt5MultimediaWidgets_DEBUG' : not found 
Checking for 'Qt5Network_DEBUG'           : not found 
Checking for 'Qt5Xml_DEBUG'               : not found 
Checking for 'Qt5ScriptTools_DEBUG'       : not found 
Checking for 'Qt5XmlPatterns_DEBUG'       : not found 
Checking for 'Qt5EglDeviceIntegration_DEBUG' : not found 
Checking for 'Qt5Gui_DEBUG'                  : not found 
Checking for 'Qt5DBus_DEBUG'                 : not found 
Checking for 'Qt53DQuickRenderer_DEBUG'      : not found 
Checking for 'Qt5Core_DEBUG'                 : not found 
Checking for 'Qt53DInput_DEBUG'              : not found 
Checking for 'Qt5MultimediaQuick_p_DEBUG'    : not found 
Checking for 'Qt5Sql_DEBUG'                  : not found 
Checking for 'Qt5OpenGL_DEBUG'               : not found 
Checking for 'Qt5CLucene_DEBUG'              : not found 
Checking for 'Qt5QuickTest_DEBUG'            : not found 
Checking for 'Qt5PrintSupport_DEBUG'         : not found 
Checking for 'Qt5Svg_DEBUG'                  : not found 
Checking for 'Qt53DQuick_DEBUG'              : not found 
Checking for 'Qt5Core_DEBUG'                 : not found 
Checking for 'Qt5Nfc_DEBUG'                  : not found 
Checking for 'Qt5Quick_DEBUG'                : not found 
Checking for 'Qt5Bluetooth_DEBUG'            : not found 
Checking for 'Qt5DBus_DEBUG'                 : not found 
Checking for 'Qt5Designer_DEBUG'             : not found 
Checking for 'Qt5WebKitWidgets_DEBUG'        : not found 
Checking for 'Qt5Test_DEBUG'                 : not found 
Checking for 'Qt53Support_DEBUG'             : not found 
Checking for 'Qt5ExtSerialPort_DEBUG'        : not found 
Checking for 'Qt5XcbQpa_DEBUG'               : not found 
Checking for 'Qt5QuickParticles_DEBUG'       : not found 
Checking for 'Qt5Xml_DEBUG'                  : not found 
Checking for 'Qt5DesignerComponents_DEBUG'   : not found 
Checking for 'Qt53DRenderer_DEBUG'           : not found 
Checking for 'Qt5Test_DEBUG'                 : not found 
Checking for 'Qt5Help_DEBUG'                 : not found 
Checking for 'Qt53DCore_DEBUG'               : not found 
Checking for 'Qt53DCollision_DEBUG'          : not found 
Checking for 'Qt5WebKit_DEBUG'               : not found 
Checking for 'Qt5Designer_DEBUG'             : not found 
Checking for 'Qt5CLucene_DEBUG'              : not found 
Checking for 'Qt5Qml_DEBUG'                  : not found 
Checking for 'Qt5Sql_DEBUG'                  : not found 
Checking for 'Qt5Svg_DEBUG'                  : not found 
Checking for 'Qt5Widgets_DEBUG'              : not found 
Checking for 'Qt5Declarative_DEBUG'          : not found 
Checking for 'Qt5Network_DEBUG'              : not found 
Checking for 'Qt5QuickWidgets_DEBUG'         : not found 
Checking for 'Qt53DLogic_DEBUG'              : not found 
Checking for 'Qt5DesignerComponents_DEBUG'   : not found 
Checking for 'Qt5WebKit_DEBUG'               : not found 
Checking for 'Qt5Help_DEBUG'                 : not found 
Checking for 'Qt5OpenGL'                     : yes 
Checking for 'Qt5Concurrent'                 : yes 
Checking for 'Qt5Script'                     : yes 
Checking for 'Qt5Multimedia'                 : yes 
Checking for 'Qt5ScriptTools'                : yes 
Checking for 'Qt5Script'                     : yes 
Checking for 'Qt5Gui'                        : yes 
Checking for 'Qt5MultimediaWidgets'          : yes 
Checking for 'Qt5Network'                    : yes 
Checking for 'Qt5Xml'                        : yes 
Checking for 'Qt5ScriptTools'                : yes 
Checking for 'Qt5XmlPatterns'                : not found 
Checking for 'Qt5EglDeviceIntegration'       : yes 
Checking for 'Qt5Gui'                        : yes 
Checking for 'Qt5DBus'                       : yes 
Checking for 'Qt53DQuickRenderer'            : yes 
Checking for 'Qt5Core'                       : yes 
Checking for 'Qt53DInput'                    : yes 
Checking for 'Qt5MultimediaQuick_p'          : yes 
Checking for 'Qt5Sql'                        : yes 
Checking for 'Qt5OpenGL'                     : yes 
Checking for 'Qt5CLucene'                    : yes 
Checking for 'Qt5QuickTest'                  : yes 
Checking for 'Qt5PrintSupport'               : yes 
Checking for 'Qt5Svg'                        : yes 
Checking for 'Qt53DQuick'                    : yes 
Checking for 'Qt5Core'                       : yes 
Checking for 'Qt5Nfc'                        : yes 
Checking for 'Qt5Quick'                      : yes 
Checking for 'Qt5Bluetooth'                  : yes 
Checking for 'Qt5DBus'                       : yes 
Checking for 'Qt5Designer'                   : not found 
Checking for 'Qt5WebKitWidgets'              : yes 
Checking for 'Qt5Test'                       : yes 
Checking for 'Qt53Support'                   : not found 
Checking for 'Qt5ExtSerialPort'              : not found 
Checking for 'Qt5XcbQpa'                     : yes 
Checking for 'Qt5QuickParticles'             : yes 
Checking for 'Qt5Xml'                        : yes 
Checking for 'Qt5DesignerComponents'         : not found 
Checking for 'Qt53DRenderer'                 : yes 
Checking for 'Qt5Test'                       : yes 
Checking for 'Qt5Help'                       : yes 
Checking for 'Qt53DCore'                     : yes 
Checking for 'Qt53DCollision'                : yes 
Checking for 'Qt5WebKit'                     : yes 
Checking for 'Qt5Designer'                   : not found 
Checking for 'Qt5CLucene'                    : yes 
Checking for 'Qt5Qml'                        : yes 
Checking for 'Qt5Sql'                        : yes 
Checking for 'Qt5Svg'                        : yes 
Checking for 'Qt5Widgets'                    : yes 
Checking for 'Qt5Declarative'                : not found 
Checking for 'Qt5Network'                    : yes 
Checking for 'Qt5QuickWidgets'               : yes 
Checking for 'Qt53DLogic'                    : yes 
Checking for 'Qt5DesignerComponents'         : not found 
Checking for 'Qt5WebKit'                     : yes 
Checking for 'Qt5Help'                       : yes 
See if Qt files compile                      : no 
See if Qt files compile with -fPIE           : no 
See if Qt files compile with -fPIC           : yes 
Checking for code snippet                    : yes 
Checking for program 'python3'               : /usr/bin/python3 
Checking for program 'python'                : /usr/bin/python3 
Could not find Qt5WebEngineWidgets - check `pkg-config --libs Qt5WebEngineWidgets`
(complete log in /...

**Comment by ita1024** [comment]
I am afraid that you may have to upgrade your system for this :-/

**Comment by ruediman** [comment]
Ok, thanks!
Can we compile the packages `libqt5webenginewidgets5-dev `and `qtwebengine5-dev` from source?

**Comment by ita1024** [comment]
I have no such information.

**Comment by ruediman** [comment]
Ok, thank you anyway.
