### ISSUE TITLE
Build dependency qt5svg not found

### ISSUE THREAD

**Issue by gorgonz** [ita1024/semantik#72]
I tried to build an actual version under opensuse leap 42.2 (64). configure stops with
Could not find Qt5Svg - Semantik requires Qt >= 5

YaST reports, that the libs resp. links are here (and they are):
/usr/lib64/libQt5Svg.so.5
/usr/lib64/libQt5Svg.so.5.6
/usr/lib64/libQt5Svg.so.5.6.1 (the real file)

Other dependencies were matched:

```
Checking for 'Qt5OpenGL'                 : yes 
Checking for 'Qt5Sql'                    : yes 
Checking for 'Qt5Gui'                    : yes 
Checking for 'Qt5Test'                   : yes 
Checking for 'Qt5Concurrent'             : yes 
Checking for 'Qt5Core'                   : yes 
Checking for 'Qt5PrintSupport'           : yes 
Checking for 'Qt5Widgets'                : yes 
Checking for 'Qt5Xml'                    : yes 
Checking for 'Qt5DBus'                   : yes 
Checking for 'Qt5Network'                : yes 

```

Maybe it needs some adjustment to find the version

For the time being it could be a help for me to get a workaround ;-)

**Comment by gorgonz** [comment]
Well, the subject has changed. Problem was, that no *-devel package was installed for this special package. It took my a little time to find it, because it has a different name. Same situation also happens with the webengine package. The correct names for these packages are:
```
libqt5-qtsvg-devel
libqt5-qtwebengine-devel
```
Maybe it is possible to add this info for opensuse users into the install doc

**Comment by gorgonz** [comment]
Finally I made it to get an successful build. Again for doc: You may have to install more dev-packages, here are the correct names in opensuse leap 42.2:
```
python3-devel
kio-devel (and its dependencies)
kiconthemes-devel
ki18n-devel
kdelibs4support-devel (and its dependencies)
```

**Comment by ita1024** [comment]
This is documented in the README file; rpm files for openSUSE 42.3 are also published now:
https://waf.io/semantik.html
