### ISSUE TITLE
any chance to get this to work on WIN10 *cough*

### ISSUE THREAD

**Issue by ruediman** [ita1024/semantik#73]
Using waf configure. Not sure which python i am using (python 3.6.0 is in the environment-path. Python 2.7 installed, though).
Friendly reminder from the compiler: 
`... Semantik cannot work on win32, please install a Linux system from http://www.opensuse.org`

**Comment by c-cesar** [comment]
Semantik uses KDE Frameworks 5 and some old kdelibs classes in KDELibs4Support. Compiling on Windows should be possible using https://community.kde.org/Windows but would be a lot of work to setup the build system. 
There are some minor things, like system paths that can be a issue and some road blocks, like the way Semantik calls other programs to perform tasks like exporting documents. I don't know what is the current solution. Possibilities are QProcess, IPC, system calls...
So, it is not impossible, but requires some investigation and work.
Can you investigate this?
