### ISSUE TITLE
Node with the text "Vacío"

### ISSUE THREAD

**Issue by jorgedavilalopez** [ita1024/semantik#74]
Hello,
I am using 

Semantik Versión 0.8.4, KDE 4.14.16 on Kubuntu 16.04.3 LTS and when a new map is created every node do not show the text entered just tthe word "Vacío".

Thanks,
Jorge Dávila.

**Comment by ita1024** [comment]
Select one and type "enter" to start editing it.

**Comment by jorgedavilalopez** [comment]
Thanks for your answer.
