### ISSUE TITLE
No hicolor fallback icons

### ISSUE THREAD

**Issue by kyrios123** [ita1024/semantik#78]
I just built semantik 1.0.1 and I do notice that there are only icons under `/usr/share/icons/oxygen`. It would be nice to add `/usr/share/icons/hicolor` as it is the fallback location (i.e. I installed semantik on a GTK-based desktop and it cannot find icons for the `.desktop` shortcuts)

**Comment by ita1024** [comment]
There were a lot of bugs a while ago that made setting hicolor not work at all, but it seems fixed. Can you retry with the latest source code from the master branch?

**Comment by kyrios123** [comment]
As it's for packaging to add in a repository, I don't can't use master.
FWIW, I made symbolic links as a workaround and it works fine.

**Comment by ita1024** [comment]
I am kindly asking you to help with testing the changes, but i guess that it is too much.
