### ISSUE TITLE
Saving this file only results in Broken Document message

### ISSUE THREAD

**Issue by xantof** [ita1024/semantik#79]
Dear Thomas,

Long time appreciative Semantik user here.    V1.0.0 on Ubuntu MATE 17.10

Everytime I save the attached file, it gets truncated resulting in a Broken File the next time I try to open it.  

This is the end of my file.

> link p="18" v="31"
> link p="18" v="32"
> lin

I am able to (temporarily) repair it as per your instructions here : [https://github.com/ita1024/semantik/issues/45](url) by adding the closing </semantik> tag.  But the same thing happens the next time I save it.  It happens on different computers.

I can start new projects or open old ones and save/open them without encountering this problem.  When I created this project, I remember having had a (possible) cache issue with what seemed a read/write problem to the tmp folder.  But I was able to continue working on my project.
When I want to save a project, Semantik opens the file manager to the tmp folder and I have to navigate to my user directory. I suspect the probable origin/cause of my problem lies somewhere around there.

File that opens once (after patching closing </semantik> tag) : 
[opensonce.tar.gz](https://github.com/ita1024/semantik/files/1600214/opensonce.tar.gz)

File that gives Broken Document message : 
[brkndoc.tar.gz](https://github.com/ita1024/semantik/files/1600217/brkndoc.tar.gz)

(they are sem files, just replace the extension)
This is not a priority or blockage issue for me as you have showed me how to recover my data and I started a project anew.    However, it made me feel uncomfortable for a while as I was not sure I could use Semantik safely.  So I thought I'd mention it.  And I am curious to know why it happens to this file only.

Thanks again for Semantik,
Stephan

**Comment by ita1024** [comment]
Are you able to build and install the application yourself? If yes, use the master branch because there are quite a few useful changes in the latest versions. Else, replace your system file with this version https://github.com/ita1024/semantik/blob/master/src/templates/semantik.sem.py and give it a try.

**Comment by xantof** [comment]
YES !  After I posted I read your changelog about saving files that had accented characters.  This file is one that contains some (French -- all my previous projects were in English).  I just built the latest (HOT - I can still feel the heat of your finger on the keyboard) 1.0.2 version and it does not truncate my file anymore. 
Thousand thanks, you can close this issue.
Stephan

**Comment by ita1024** [comment]
FYI, Ubuntu 17.10 snapshot packages are now published for testing purposes:
https://waf.io/rpms/semantik_1.0.2-4_amd64.deb
