### ISSUE TITLE
Strange includes

### ISSUE THREAD

**Issue by c-cesar** [ita1024/semantik#81]
Browsing in the code I found some strange includes, like:
```cpp
%: ifndef DIAGRAM_WIDGET_H
#define DIAGRAM_WIDGET_H

%: inc\
lude "con.\
h"

#inc\
lude <QFrame>

%: include<QUrl>
```
This seems to me as noise left from a automated code update, and I made a [commit](https://github.com/c-cesar/semantik/commit/dd4e9838de399dfe98b00c215b924eac96e5d160) to fix, but as I'm not sure, not a PR yet.

Want you to merge it or it have some meaning?

**Comment by ita1024** [comment]
There are a lot of includes so such changes would make the file history less readable. Please do not make such changes because they would only complicate the code and not add new functionality.
