### ISSUE TITLE
Failure when opening .mm file from kdissert

### ISSUE THREAD

**Issue by brycepg** [ita1024/semantik#83]
Looks like `kdissert.py` should be running python2.7 but is using python3.x

I compiled semantik on fedora-26

The `kdissert.py` file has a shebang of `#!/usr/bin/env python` and that points to python 2.7.13 on my system. When I fix this error, I find other errors indicative that this file is meant for python2.7
```
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "/usr/share/semantik/filters/kdissert.py", line 5, in <module>
    import os, sys, tarfile, StringIO
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by ita1024** [comment]
The runtime is fine, the problem is that the module has not been ported to Python3 yet. Try and update your copy from the master branch.

**Comment by brycepg** [comment]
It works now, thanks!
